# Regex that gets the information out of the @TCSGotthard tweets
tweet_jam_regex: .*?- (.*?) Richtung Gotthard.*?(\d*) km Stau.*?(\d*) (Stunden|Minuten)
tweet_info_regex: "#A2 - (.*)"
tweet_closed_regex: .*?- (.*?)(:?Richtung Gotthard)?(.*gesperrt.*)